In [20]:
import numpy as np

In [76]:
# Создадим двумерный массив из списка, используя тип данных из NumPy.
td_arr = np.array([[11, 22, 33, 44], [1, 2, 3, 4], [5, 10, 15, 20]])
# Создадим ещё один массив, используя функцию заполнения массива единицами.
ones_arr = np.ones(9)

In [77]:
# Выведем первый созданный массив.
print(td_arr)
# Выведем второй созданный массив, изменив его форму методом reshape.
print(ones_arr.reshape(3, 3))

[[11 22 33 44]
 [ 1  2  3  4]
 [ 5 10 15 20]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [78]:
# Выводим информацию о созданном массиве: вывод атрибута shape означает, что
# в массиве три списка, в каждом из которых по четыре элемента, а вывод dtype
# означает, что в массиве содержатся числовые значения.
print(td_arr.shape, td_arr.dtype)

(3, 4) int64


In [79]:
# Выводим четвёртый элемент из второго вложенного списка
print(td_arr[1][3])
# Выводим срез, состоящий из каждого последнего элемента из всех трёх подмножеств
print(td_arr[:3, :2:-1])

4
[[44]
 [ 4]
 [20]]


In [81]:
# Проведём поэлементное сложение: прибавим к массиву такой же массив, умноженный на 0.1
print(td_arr + td_arr * 0.1)

[[12.1 24.2 36.3 48.4]
 [ 1.1  2.2  3.3  4.4]
 [ 5.5 11.  16.5 22. ]]


In [ ]:
# Вычисляем максимальный элемент всего массива.
print(td_arr.max())
# Вычисляем суммы элементов для каждого столбца.
print(td_arr.sum(axis=0))
# Вычисляем средние значения элементов для каждой строки.
print(td_arr.mean(axis=1))

44
[17 34 51 68]
[27.5  2.5 12.5]
